"""0001_initial

Revision ID: 5f42e5bb1bda
Revises:
Create Date: 2026-08-01 00:35:26.000450

"""

from typing import Union
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f42e5bb1bda"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("book_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("isbn", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("total_copies", sa.Integer(), nullable=False),
        sa.Column("available_copies", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("issue_count", sa.Integer(), nullable=False),
        sa.Column("added_on", sa.String(length=32), nullable=False),
        sa.Column("publisher", sa.String(length=255), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("release_date", sa.String(length=32), nullable=False),
        sa.Column("cover_image", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("series_name", sa.String(length=255), nullable=False),
        sa.Column("series_order", sa.Integer(), nullable=False),
        sa.Column("cover_url", sa.Text(), nullable=False),
        sa.Column("cover_fetched", sa.Boolean(), nullable=False),
        sa.Column("cover_source", sa.String(length=32), nullable=False),
        sa.Column("dominant_color", sa.String(length=16), nullable=False),
        sa.Column("genres", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("book_id"),
    )
    op.create_index(op.f("ix_books_added_on"), "books", ["added_on"], unique=False)
    op.create_index("ix_books_author", "books", ["author"], unique=False)
    op.create_index(
        "ix_books_category_avail",
        "books",
        ["category", "available_copies"],
        unique=False,
    )
    op.create_index(op.f("ix_books_is_deleted"), "books", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=False)
    op.create_index(
        op.f("ix_books_issue_count"), "books", ["issue_count"], unique=False
    )
    op.create_index("ix_books_title", "books", ["title"], unique=False)
    op.create_table(
        "communities",
        sa.Column("community_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("members", sa.JSON(), nullable=False),
        sa.Column("max_members", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("community_id"),
    )
    op.create_index(op.f("ix_communities_name"), "communities", ["name"], unique=False)
    op.create_table(
        "series",
        sa.Column("series_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("total_books", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("series_id"),
    )
    op.create_index(op.f("ix_series_name"), "series", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("membership_status", sa.String(length=16), nullable=False),
        sa.Column("membership_expiry", sa.String(length=32), nullable=False),
        sa.Column("books_issued", sa.JSON(), nullable=False),
        sa.Column("unpaid_fine", sa.Float(), nullable=False),
        sa.Column("registered_on", sa.String(length=32), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.Column("profile_picture", sa.Text(), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=128), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("favorite_genres", sa.JSON(), nullable=False),
        sa.Column("favorite_books", sa.JSON(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("lock_until", sa.String(length=32), nullable=True),
        sa.Column("theme", sa.String(length=16), nullable=False),
        sa.Column("font_size", sa.String(length=16), nullable=False),
        sa.Column("email_notifications", sa.Boolean(), nullable=False),
        sa.Column("push_notifications", sa.Boolean(), nullable=False),
        sa.Column("notify_on_comment", sa.Boolean(), nullable=False),
        sa.Column("notify_on_like", sa.Boolean(), nullable=False),
        sa.Column("notify_on_follow", sa.Boolean(), nullable=False),
        sa.Column("notify_on_issue_return", sa.Boolean(), nullable=False),
        sa.Column("notify_on_overdue", sa.Boolean(), nullable=False),
        sa.Column("notify_on_due_reminder", sa.Boolean(), nullable=False),
        sa.Column("privacy_show_activity", sa.Boolean(), nullable=False),
        sa.Column("privacy_show_wishlist", sa.Boolean(), nullable=False),
        sa.Column("privacy_show_bookmarks", sa.Boolean(), nullable=False),
        sa.Column("privacy_profile_visibility", sa.String(length=16), nullable=False),
        sa.Column("privacy_show_email", sa.Boolean(), nullable=False),
        sa.Column("reading_default_rating", sa.String(length=16), nullable=False),
        sa.Column("reading_goal_type", sa.String(length=16), nullable=False),
        sa.Column("reading_default_goal", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(
        op.f("ix_users_membership_status"), "users", ["membership_status"], unique=False
    )
    op.create_index("ix_users_name", "users", ["name"], unique=False)
    op.create_index(
        op.f("ix_users_registered_on"), "users", ["registered_on"], unique=False
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(
        "ix_users_role_status", "users", ["role", "membership_status"], unique=False
    )
    op.create_index(
        op.f("ix_users_unpaid_fine"), "users", ["unpaid_fine"], unique=False
    )
    op.create_table(
        "bookshelves",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("books", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bookshelves_user_id"), "bookshelves", ["user_id"], unique=False
    )
    op.create_table(
        "diary_entries",
        sa.Column("entry_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("book_id", sa.String(length=64), nullable=False),
        sa.Column("date_read", sa.String(length=32), nullable=False),
        sa.Column("rating_label", sa.String(length=32), nullable=False),
        sa.Column("star_rating", sa.Integer(), nullable=False),
        sa.Column("diary_text", sa.Text(), nullable=False),
        sa.Column("pages_read", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_index(
        op.f("ix_diary_entries_date_read"), "diary_entries", ["date_read"], unique=False
    )
    op.create_index(
        op.f("ix_diary_entries_user_id"), "diary_entries", ["user_id"], unique=False
    )
    op.create_index(
        "ix_diary_user_date", "diary_entries", ["user_id", "date_read"], unique=False
    )
    op.create_table(
        "fines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("book_id", sa.String(length=64), nullable=False),
        sa.Column("fine", sa.Float(), nullable=False),
        sa.Column("date", sa.String(length=32), nullable=False),
        sa.Column("paid", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fines_paid"), "fines", ["paid"], unique=False)
    op.create_index(op.f("ix_fines_user_id"), "fines", ["user_id"], unique=False)
    op.create_index("ix_fines_user_paid", "fines", ["user_id", "paid"], unique=False)
    op.create_table(
        "follows",
        sa.Column("follow_id", sa.String(length=64), nullable=False),
        sa.Column("follower_id", sa.String(length=64), nullable=False),
        sa.Column("following_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["following_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("follow_id"),
        sa.UniqueConstraint("follower_id", "following_id", name="uq_follow_pair"),
    )
    op.create_index(
        op.f("ix_follows_follower_id"), "follows", ["follower_id"], unique=False
    )
    op.create_index("ix_follows_following", "follows", ["following_id"], unique=False)
    op.create_index(
        op.f("ix_follows_following_id"), "follows", ["following_id"], unique=False
    )
    op.create_table(
        "gamification",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("streak", sa.Integer(), nullable=False),
        sa.Column("badges", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "notifications",
        sa.Column("notif_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("notif_id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_read"), "notifications", ["read"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_index(
        "ix_notifs_user_read", "notifications", ["user_id", "read"], unique=False
    )
    op.create_table(
        "posts",
        sa.Column("post_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("book_ids", sa.JSON(), nullable=False),
        sa.Column("image_urls", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.Column("likes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_index(op.f("ix_posts_created_at"), "posts", ["created_at"], unique=False)
    op.create_index(
        "ix_posts_user_created", "posts", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_posts_user_id"), "posts", ["user_id"], unique=False)
    op.create_table(
        "reading_challenges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("goal", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "year", name="uq_challenge_user_year"),
    )
    op.create_index(
        op.f("ix_reading_challenges_user_id"),
        "reading_challenges",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_challenges_year"), "reading_challenges", ["year"], unique=False
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.book_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id", "user_id", name="uq_reservation_book_user"),
    )
    op.create_index(
        op.f("ix_reservations_book_id"), "reservations", ["book_id"], unique=False
    )
    op.create_index(
        "ix_reservations_book_pos",
        "reservations",
        ["book_id", "position"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reservations_user_id"), "reservations", ["user_id"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("review_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("book_id", sa.String(length=32), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("review_text", sa.Text(), nullable=False),
        sa.Column("shelf", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.book_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("review_id"),
        sa.UniqueConstraint("user_id", "book_id", name="uq_review_user_book"),
    )
    op.create_index(op.f("ix_reviews_book_id"), "reviews", ["book_id"], unique=False)
    op.create_index(
        "ix_reviews_book_rating", "reviews", ["book_id", "rating"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_created_at"), "reviews", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("txn_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("book_id", sa.String(length=32), nullable=False),
        sa.Column("issue_date", sa.String(length=32), nullable=False),
        sa.Column("due_date", sa.String(length=32), nullable=False),
        sa.Column("return_date", sa.String(length=32), nullable=True),
        sa.Column("fine", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.book_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("txn_id"),
    )
    op.create_index(
        op.f("ix_transactions_book_id"), "transactions", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_due_date"), "transactions", ["due_date"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_issue_date"), "transactions", ["issue_date"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_return_date"),
        "transactions",
        ["return_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_txns_open_due", "transactions", ["return_date", "due_date"], unique=False
    )
    op.create_index(
        "ix_txns_user_open", "transactions", ["user_id", "return_date"], unique=False
    )
    op.create_table(
        "wishlist_suggestions",
        sa.Column("suggestion_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("isbn", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("upvotes", sa.JSON(), nullable=False),
        sa.Column("downvotes", sa.JSON(), nullable=False),
        sa.Column("comments", sa.JSON(), nullable=False),
        sa.Column("admin_notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("suggestion_id"),
    )
    op.create_index(
        op.f("ix_wishlist_suggestions_created_at"),
        "wishlist_suggestions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wishlist_suggestions_status"),
        "wishlist_suggestions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wishlist_suggestions_user_id"),
        "wishlist_suggestions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "comments",
        sa.Column("comment_id", sa.String(length=64), nullable=False),
        sa.Column("post_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("likes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.post_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_index(
        op.f("ix_comments_created_at"), "comments", ["created_at"], unique=False
    )
    op.create_index(
        "ix_comments_post_created", "comments", ["post_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_comments_post_id"), "comments", ["post_id"], unique=False)
    op.create_index(op.f("ix_comments_user_id"), "comments", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_user_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_post_id"), table_name="comments")
    op.drop_index("ix_comments_post_created", table_name="comments")
    op.drop_index(op.f("ix_comments_created_at"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(
        op.f("ix_wishlist_suggestions_user_id"), table_name="wishlist_suggestions"
    )
    op.drop_index(
        op.f("ix_wishlist_suggestions_status"), table_name="wishlist_suggestions"
    )
    op.drop_index(
        op.f("ix_wishlist_suggestions_created_at"), table_name="wishlist_suggestions"
    )
    op.drop_table("wishlist_suggestions")
    op.drop_index("ix_txns_user_open", table_name="transactions")
    op.drop_index("ix_txns_open_due", table_name="transactions")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_return_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_issue_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_due_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_book_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_created_at"), table_name="reviews")
    op.drop_index("ix_reviews_book_rating", table_name="reviews")
    op.drop_index(op.f("ix_reviews_book_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_reservations_user_id"), table_name="reservations")
    op.drop_index("ix_reservations_book_pos", table_name="reservations")
    op.drop_index(op.f("ix_reservations_book_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(op.f("ix_reading_challenges_year"), table_name="reading_challenges")
    op.drop_index(
        op.f("ix_reading_challenges_user_id"), table_name="reading_challenges"
    )
    op.drop_table("reading_challenges")
    op.drop_index(op.f("ix_posts_user_id"), table_name="posts")
    op.drop_index("ix_posts_user_created", table_name="posts")
    op.drop_index(op.f("ix_posts_created_at"), table_name="posts")
    op.drop_table("posts")
    op.drop_index("ix_notifs_user_read", table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("gamification")
    op.drop_index(op.f("ix_follows_following_id"), table_name="follows")
    op.drop_index("ix_follows_following", table_name="follows")
    op.drop_index(op.f("ix_follows_follower_id"), table_name="follows")
    op.drop_table("follows")
    op.drop_index("ix_fines_user_paid", table_name="fines")
    op.drop_index(op.f("ix_fines_user_id"), table_name="fines")
    op.drop_index(op.f("ix_fines_paid"), table_name="fines")
    op.drop_table("fines")
    op.drop_index("ix_diary_user_date", table_name="diary_entries")
    op.drop_index(op.f("ix_diary_entries_user_id"), table_name="diary_entries")
    op.drop_index(op.f("ix_diary_entries_date_read"), table_name="diary_entries")
    op.drop_table("diary_entries")
    op.drop_index(op.f("ix_bookshelves_user_id"), table_name="bookshelves")
    op.drop_table("bookshelves")
    op.drop_index(op.f("ix_users_unpaid_fine"), table_name="users")
    op.drop_index("ix_users_role_status", table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_registered_on"), table_name="users")
    op.drop_index("ix_users_name", table_name="users")
    op.drop_index(op.f("ix_users_membership_status"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_series_name"), table_name="series")
    op.drop_table("series")
    op.drop_index(op.f("ix_communities_name"), table_name="communities")
    op.drop_table("communities")
    op.drop_index("ix_books_title", table_name="books")
    op.drop_index(op.f("ix_books_issue_count"), table_name="books")
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.drop_index(op.f("ix_books_is_deleted"), table_name="books")
    op.drop_index("ix_books_category_avail", table_name="books")
    op.drop_index("ix_books_author", table_name="books")
    op.drop_index(op.f("ix_books_added_on"), table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
