"""Seed data constants for user generation."""

FIRST_NAMES_MALE = [
    "Aarav",
    "Vivaan",
    "Aditya",
    "Vihaan",
    "Arjun",
    "Sai",
    "Rohit",
    "Aryan",
    "Raj",
    "Amit",
    "Suresh",
    "Ramesh",
    "Vikram",
    "Anil",
    "Sunil",
    "Manoj",
    "Sanjay",
    "Rajesh",
    "Deepak",
    "Ashok",
    "Vijay",
    "Kishore",
    "Ravi",
    "Prakash",
    "Ganesh",
    "Dinesh",
    "Mahesh",
    "Vinod",
    "Harish",
    "Naveen",
    "Prasad",
    "Siddharth",
    "Karan",
    "Harsh",
    "Yash",
    "Om",
    "Rohan",
    "Kunal",
    "Abhishek",
    "Nikhil",
    "Shubham",
    "Varun",
    "Rahul",
    "Aniket",
    "Pranav",
    "Dhruv",
    "Tanmay",
    "Ishaan",
    "Shaurya",
    "Yash",
    "Reyansh",
    "Dhruv",
    "Kabir",
    "Rudra",
    "Ayaan",
    "Krishna",
    "Shiv",
    "Daksh",
    "Atharv",
    "Laksh",
    "Shlok",
    "Parth",
    "Arnav",
    "Neil",
    "Hrithik",
    "Ranbir",
    "Akshay",
    "Shahid",
    "Aamir",
    "Salman",
    "Irrfan",
    "Nawazuddin",
    "Rajkummar",
    "Ayushmann",
    "Vicky",
    "Rajiv",
    "Arvind",
    "Mohan",
    "Shankar",
    "Babu",
    "Murali",
    "Srinivas",
    "Venkatesh",
    "Narayana",
    "Subramaniam",
    "Padmanabhan",
    "Balaji",
    "Prithvi",
    "Chandan",
    "Hemant",
    "Jagdish",
    "Kamal",
    "Lalit",
    "Murugan",
    "Natarajan",
    "Pandian",
    "Ramachandran",
    "Selvam",
    "Thirumalai",
    "Uday",
    "Velayudham",
    "Yogesh",
    "Chandrasekhar",
    "Venugopal",
    "Sridhar",
]

FIRST_NAMES_FEMALE = [
    "Aanya",
    "Aadhya",
    "Ananya",
    "Diya",
    "Ishita",
    "Janvi",
    "Kavya",
    "Neha",
    "Priya",
    "Riya",
    "Saanvi",
    "Tanvi",
    "Varsha",
    "Yashvi",
    "Aishwarya",
    "Deepika",
    "Katrina",
    "Anushka",
    "Shraddha",
    "Alia",
    "Kareena",
    "Madhuri",
    "Kajol",
    "Rani",
    "Vidya",
    "Priyanka",
    "Sonam",
    "Anupama",
    "Lata",
    "Asha",
    "Mira",
    "Anita",
    "Sunita",
    "Kavita",
    "Nalini",
    "Vasundhara",
    "Lakshmi",
    "Saraswati",
    "Durga",
    "Kali",
    "Parvati",
    "Sita",
    "Radha",
    "Ganga",
    "Yamuna",
    "Shakti",
    "Devi",
    "Mala",
    "Geeta",
    "Seeta",
    "Rekha",
    "Hema",
    "Jaya",
    "Shabana",
    "Waheeda",
    "Meena",
    "Kumari",
    "Selvi",
    "Bhavani",
    "Padmini",
    "Rohini",
    "Shobana",
    "Urmila",
    "Chandrika",
    "Nandini",
    "Padma",
    "Revathi",
    "Shyamala",
    "Thulasi",
    "Vijayalakshmi",
    "Yamini",
    "Swati",
    "Mrunal",
    "Tara",
    "Zara",
    "Inaya",
    "Myra",
    "Anaya",
    "Kyra",
    "Naira",
    "Alisha",
    "Eshani",
    "Gauri",
    "Harini",
    "Jasmine",
    "Kriti",
    "Lavanya",
    "Navya",
    "Ojaswini",
    "Pooja",
    "Rashmi",
    "Shreya",
]

LAST_NAMES = [
    "Sharma",
    "Verma",
    "Gupta",
    "Kumar",
    "Singh",
    "Patel",
    "Reddy",
    "Rao",
    "Nair",
    "Menon",
    "Iyer",
    "Iyengar",
    "Joshi",
    "Deshmukh",
    "Kulkarni",
    "Desai",
    "Shah",
    "Mehta",
    "Patil",
    "Pawar",
    "Yadav",
    "Jha",
    "Mishra",
    "Tiwari",
    "Pandey",
    "Dubey",
    "Saxena",
    "Srivastava",
    "Agarwal",
    "Kapoor",
    "Malhotra",
    "Chopra",
    "Bajaj",
    "Bhalla",
    "Gandhi",
    "Modi",
    "Trivedi",
    "Bhatt",
    "Pandya",
    "Solanki",
    "Chauhan",
    "Rathore",
    "Shekhawat",
    "Purohit",
    "Soni",
    "Arya",
    "Rawat",
    "Bisht",
    "Negi",
    "Rana",
    "Thapa",
    "Gurung",
    "Tamang",
    "Sherpa",
    "Lama",
    "Ghai",
    "Sood",
    "Batra",
    "Khanna",
    "Sethi",
    "Arora",
    "Sachdev",
    "Juneja",
    "Bhasin",
    "Chadha",
    "Dhawan",
    "Gulati",
    "Kohli",
    "Malik",
    "Narang",
    "Oberoi",
    "Purie",
    "Sabharwal",
    "Tandon",
    "Uppal",
    "Vohra",
    "Wahi",
    "Bansal",
    "Garg",
    "Mittal",
    "Singhal",
    "Goyal",
    "Poddar",
    "Lodha",
    "Chordia",
    "Kothari",
    "Bothra",
    "Daga",
    "Somani",
    "Kedia",
    "Bhardwaj",
    "Mukherjee",
    "Banerjee",
    "Chatterjee",
    "Ghosh",
    "Das",
    "Bose",
    "Sen",
    "Roy",
    "Chakraborty",
    "Sarkar",
    "Pal",
    "Majumdar",
    "Dutta",
    "Saha",
    "Bhowmik",
    "Dey",
    "Bhowmick",
]

CITIES = [
    ("Mumbai", "Maharashtra"),
    ("Delhi", "Delhi"),
    ("Bangalore", "Karnataka"),
    ("Hyderabad", "Telangana"),
    ("Ahmedabad", "Gujarat"),
    ("Chennai", "Tamil Nadu"),
    ("Kolkata", "West Bengal"),
    ("Pune", "Maharashtra"),
    ("Jaipur", "Rajasthan"),
    ("Lucknow", "Uttar Pradesh"),
    ("Surat", "Gujarat"),
    ("Nagpur", "Maharashtra"),
    ("Indore", "Madhya Pradesh"),
    ("Bhopal", "Madhya Pradesh"),
    ("Patna", "Bihar"),
    ("Vadodara", "Gujarat"),
    ("Coimbatore", "Tamil Nadu"),
    ("Chandigarh", "Chandigarh"),
    ("Mysore", "Karnataka"),
    ("Thiruvananthapuram", "Kerala"),
    ("Guwahati", "Assam"),
    ("Ranchi", "Jharkhand"),
    ("Bhubaneswar", "Odisha"),
    ("Vishakhapatnam", "Andhra Pradesh"),
    ("Agra", "Uttar Pradesh"),
    ("Varanasi", "Uttar Pradesh"),
    ("Udaipur", "Rajasthan"),
    ("Kochi", "Kerala"),
    ("Goa", "Goa"),
    ("Shimla", "Himachal Pradesh"),
    ("Darjeeling", "West Bengal"),
    ("Pondicherry", "Puducherry"),
    ("Amritsar", "Punjab"),
    ("Jodhpur", "Rajasthan"),
    ("Nasik", "Maharashtra"),
    ("Aurangabad", "Maharashtra"),
    ("Madurai", "Tamil Nadu"),
    ("Trichy", "Tamil Nadu"),
    ("Salem", "Tamil Nadu"),
    ("Vellore", "Tamil Nadu"),
    ("Mangalore", "Karnataka"),
    ("Hubli", "Karnataka"),
    ("Guntur", "Andhra Pradesh"),
    ("Tirupati", "Andhra Pradesh"),
    ("Warangal", "Telangana"),
    ("Noida", "Uttar Pradesh"),
    ("Gurgaon", "Haryana"),
    ("Faridabad", "Haryana"),
    ("Dehradun", "Uttarakhand"),
    ("Haridwar", "Uttarakhand"),
]

GENRES = [
    "Fiction",
    "Non-Fiction",
    "Science",
    "Technology",
    "History",
    "Philosophy",
    "Art",
    "Biography",
    "Poetry",
    "Drama",
    "Comics",
    "Self-Help",
    "Cooking",
    "Travel",
    "Music",
    "Sports",
    "Education",
    "Reference",
    "Religion",
    "Children",
]

BIOS = [
    "Avid reader and lifelong learner. Love exploring different genres.",
    "Book lover who believes every story has something to teach us.",
    "Reading is my escape from reality. Currently on a fantasy kick.",
    "I read to travel without moving. 50+ books a year and counting.",
    "Book collector, tea drinker, and amateur philosopher.",
    "Always looking for book recommendations! Let's connect.",
    "Lost in the pages of a good book. Fiction is my first love.",
    "Reading is my superpower. Especially love Indian authors.",
    "From sci-fi to history, I read it all. Knowledge is power.",
    "Nothing beats the feeling of a new book. Let's read together!",
    "Bibliophile with a passion for literature and learning.",
    "I read so I can live a thousand lives. Book discussions welcome!",
    "On a mission to read 100 books this year. Join me!",
    "Books, coffee, and quiet mornings. That's my happy place.",
    "Curious mind, ever-expanding bookshelf. All genres welcome.",
    "Reading gives us someplace to go when we have to stay where we are.",
    "I judge books by their covers AND their content. No shame.",
    "Professional over-thinker and amateur book reviewer.",
    "My bookshelf is my greatest treasure. Love sharing finds.",
    "Exploring worlds one page at a time. #Bookstagrammer",
    "Book nerd by day, dreamer by night. Let's chat about books!",
    "I love the smell of old books and the promise of new ones.",
    "Reading is my therapy. A library card is my prescription.",
    "Every book is a new adventure waiting to happen.",
]

EMAIL_DOMAINS = [
    "gmail.com",
    "yahoo.com",
    "outlook.com",
    "hotmail.com",
    "rediffmail.com",
    "protonmail.com",
    "zoho.com",
    "icloud.com",
    "live.com",
    "fastmail.com",
    "gmx.com",
    "yandex.com",
    "mail.com",
    "bookmail.com",
    "readermail.com",
]

PHONE_PREFIXES = [
    "98765",
    "98754",
    "98123",
    "98234",
    "98345",
    "98456",
    "98567",
    "98678",
    "98989",
    "98760",
    "99887",
    "99776",
    "99665",
    "99554",
    "99443",
    "99332",
    "91234",
    "91345",
    "91456",
    "91567",
    "91678",
    "91789",
    "91890",
    "91901",
]

HOBBIES = [
    "reading",
    "writing",
    "photography",
    "cooking",
    "gardening",
    "painting",
    "traveling",
    "hiking",
    "cycling",
    "swimming",
    "yoga",
    "meditation",
    "music",
    "dancing",
    "bird watching",
    "stargazing",
    "blogging",
    "chess",
]


